### ISSUE TITLE
Solita errors out while parsing a valid IDL

### ISSUE THREAD

**Issue by SkullTech** [metaplex-foundation/solita#30]
This is the whole error

```console
/Users/sumit/.config/yarn/global/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/generate-sdk.ts:5:26 - error TS2345: Argument of type '{ version: string; name: string; instructions: { name: string; accounts: { name: string; isMut: boolean; isSigner: boolean; }[]; args: ({ name: string; type: string; } | { name: string; type: { option: string; }; })[]; }[]; ... 4 more ...; metadata: { ...; }; }' is not assignable to parameter of type 'Idl'.
  Types of property 'instructions' are incompatible.
    Type '{ name: string; accounts: { name: string; isMut: boolean; isSigner: boolean; }[]; args: ({ name: string; type: string; } | { name: string; type: { option: string; }; })[]; }[]' is not assignable to type 'IdlInstruction[]'.
      Type '{ name: string; accounts: { name: string; isMut: boolean; isSigner: boolean; }[]; args: ({ name: string; type: string; } | { name: string; type: { option: string; }; })[]; }' is not assignable to type 'IdlInstruction'.
        Types of property 'args' are incompatible.
          Type '({ name: string; type: string; } | { name: string; type: { option: string; }; })[]' is not assignable to type 'IdlInstructionArg[]'.
            Type '{ name: string; type: string; } | { name: string; type: { option: string; }; }' is not assignable to type 'IdlInstructionArg'.
              Type '{ name: string; type: string; }' is not assignable to type 'IdlInstructionArg'.
                Types of property 'type' are incompatible.
                  Type 'string' is not assignable to type 'IdlType'.

5   const gen = new Solita(idl, { formatCode: true });
                           ~~~

    at createTSError (/Users/sumit/.config/yarn/global/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/Users/sumit/.config/yarn/global/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/Users/sumit/.config/yarn/global/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/Users/sumit/.config/yarn/global/node_modules/ts-node/src/index.ts:1322:43)
    at Module.m._compile (/Users/sumit/.config/yarn/global/node_modules/ts-node/src/index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/sumit/.config/yarn/global/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticCodes: [ 2345 ]
}
```

This is the code I'm using

```typescript
import { Solita } from "@metaplex-foundation/solita";
import * as idl from "../target/idl/program.json";

const generateSdk = async () => {
  const gen = new Solita(idl, { formatCode: true });
  await gen.renderAndWriteTo("../sdk");
};

const runMain = async () => {
  try {
    await generateSdk();
    process.exit(0);
  } catch (err) {
    console.log(err);
    process.exit(1);
  }
};
```

This is the `arg` in the IDL

```json
{
  "name":"symbol",
  "type":{
    "option":"string"
  }
}
``` 

**Note:** This seems like a Typscript only error, I made it into a JS script and it ran without errors.

**Comment by thlorenz** [comment]
Yeah scripts are currently in JS (so you can run them with Nodejs directly).
However if you can make this work with TS I'd love it :)

**Comment by thlorenz** [comment]
Given that I added a [much simpler way to configure solita](https://github.com/metaplex-foundation/solita#shank--solita-example) is this still an issue for you?

**Comment by SkullTech** [comment]
> Given that I added a [much simpler way to configure solita](https://github.com/metaplex-foundation/solita#shank--solita-example) is this still an issue for you?

No it's not, thank you for the detailed README 😄 You can close this issue.

**Comment by SkullTech** [comment]
Closing 👀
