### ISSUE TITLE
solita should handle all Rust data enums

### ISSUE THREAD

**Issue by thlorenz** [metaplex-foundation/solita#64]
Currently solita [fails](https://github.com/metaplex-foundation/metaplex-program-library/runs/7159383865?check_suite_focus=true) to render the below:

```rs
pub enum CollectionDetails {
    V1 { size: u64 },
}
```

The generated IDL for this type is the below:

```json
{
  "name": "CollectionDetails",
  "type": {
    "kind": "enum",
    "variants": [
      {
        "name": "V1",
        "fields": [
          "u64"
        ]
      }
    ]
  }
}
```

I reproduced this error locally to verify that it is related to mapping the `CollectionDetails` data enum:

```
  ✖ TypeError: Cannot read properties of undefined (reading 'option')
  --------------------------------------------------------------------
    operator: error
    stack: |-
TypeError: Cannot read properties of undefined (reading 'option')
at isIdlTypeOption (/solita/test/integration/src/types.ts:193:32)
at _TypeMapper.map (/solita/test/integration/src/type-mapper.ts:166:9)
at /solita/test/integration/src/render-data-enum.ts:84:41
at Array.map (<anonymous>)
at /solita/test/integration/src/render-data-enum.ts:83:35
```

**Comment by thlorenz** [comment]
Fixed in #27
