### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by samsends** [metaplex-foundation/solita#66]
Hey! I'm running into a pesky error where I cannot use solita create instruction helper function due to serialization errors.

Here is the error output

```
  1) editions
       Is initialized!:
     TypeError: Cannot read properties of undefined (reading 'length')
      at Object.write (node_modules/@metaplex-foundation/beet/src/beets/collections.ts:39:15)
      at BeetWriter.write (node_modules/@metaplex-foundation/beet/src/read-write.ts:39:10)
      at BeetWriter.writeStruct (node_modules/@metaplex-foundation/beet/src/read-write.ts:46:12)
      at BeetStruct.serialize (node_modules/@metaplex-foundation/beet/src/struct.ts:103:12)
      at BeetStruct.write (node_modules/@metaplex-foundation/beet/src/struct.ts:63:42)
      at BeetWriter.write (node_modules/@metaplex-foundation/beet/src/read-write.ts:39:10)
      at BeetWriter.writeStruct (node_modules/@metaplex-foundation/beet/src/read-write.ts:46:12)
      at BeetArgsStruct.serialize (node_modules/@metaplex-foundation/beet/src/struct.ts:103:12)
      at Object.createCreatePlatformSettingsInstruction (editions/typescript/src/generated/instructions/createPlatformSettings.ts:73:47)
      at /Users/samsends/code/glass/editions/tests/editions.ts:53:37
      at Generator.next (<anonymous>)
      at fulfilled (tests/editions.ts:28:58)

```

And the repo to reproduce it can be found here:

https://github.com/GlassProtocol/editions

steps to reproduce:

1. yarn
2. anchor build
3. yarn solita
4. anchor test

there error throws here:

```js

    const ix = program.instructions.createCreatePlatformSettingsInstruction(
      { payer: platform_signer.publicKey, platformSettings } as CreatePlatformSettingsInstructionAccounts,
      instruction
    );

```

**Comment by samsends** [comment]
@thlorenz

**Comment by thlorenz** [comment]
Hi, could you please push the IDL that causes the issue onto a branch so I can just repro the error with it instead of checking out our project?
I'm assuming the current IDL https://github.com/GlassProtocol/editions/blob/main/editions/typescript/idl/editions.json on main is not showing this issue?

Thanks, and sorry to hear you ran into issues.

**Comment by thlorenz** [comment]
Thanks I'll have a look when I get some time.

**Comment by thlorenz** [comment]
Were you able to solve your problem or is this still an issue?
Did you adapt your code to remove the `as`s and maybe that showed an underlying problem?

**Comment by thlorenz** [comment]
Closing due to inactivity. Please LMK if this is still an issue and I'll reopen.
